const Groups = [
  {
    _id: {
      $oid: "63418486d0e121671e4d3925",
    },
    username: "johnmakola",
    groupno: "gl001",
    groupname: "Wamama Mtaani",
    grouptype: "Community",
    groupdescription:
      "A group from Matopeni Ward we support each other throup Go Round Contributions",
    groupadmin: "Allan Montari",
    grouptreasurer: "Elizabeth Kawira",
    groupsecretary: "Hadija Hassan",
    groupLocation: "Kaloleni",
    noofmembers: 10,
    grant: 500000,
    loan: 250000,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d3926",
    },
    username: "johnmakola",
    groupno: "gl002",
    groupname: "Mapendano Group",
    grouptype: "Community",
    groupdescription:
      "A Young aldults Group . Supporting our members getting started with young families through social welfare and business",
    groupadmin: "Athanus Mwelu",
    grouptreasurer: "Nimo Yusuf",
    groupsecretary: "Gufu Hassan",
    groupLocation: "Shauri Moyo",
    noofmembers: 10,
    grant: 500000,
    loan: 250000,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d3927",
    },
    username: "johnmakola",
    groupno: "gl003",
    groupname: "Ushirika Group",
    grouptype: "Business",
    groupdescription: "A Community empowerment Group for Small Businesses",
    groupadmin: "Harriet Mugure",
    grouptreasurer: "Adoyo Joseph",
    groupsecretary: "Alphonse Maina",
    groupLocation: "BuruBuru",
    noofmembers: 15,
    grant: 35000,
    loan: 87400,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d3928",
    },
    username: "johnmakola",
    groupno: "gl004",
    groupname: "Vijana na Kazi",
    grouptype: "Community",
    groupdescription: "A Youth Group for Members in College",
    groupadmin: "James Aga",
    grouptreasurer: "Patrick Muniaru",
    groupsecretary: "Grace Mukore",
    groupLocation: "Dandora",

    noofmembers: 8,
    grant: 45000,
    loan: 185000,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d3929",
    },
    username: "johnmakola",
    groupno: "gl005",
    groupname: "BodaBoda Group",
    grouptype: "Business",
    groupdescription: "A BodaBoda Members Group for Social Support",
    groupadmin: "Fowizia Hassan",
    grouptreasurer: "Hassan Jalla",
    groupsecretary: "Dahabo Ibrahim",
    groupLocation: "Huruma",

    noofmembers: 13,
    grant: 415205,
    loan: 524000,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d392a",
    },
    username: "johnmakola",
    groupno: "gl006",
    groupname: "Uzima YouthGroup",
    grouptype: "Community",
    groupdescription:
      "A Church Based Youth Group for Social and Business Support",
    groupadmin: "Allan Montari",
    grouptreasurer: "Elizabeth Kawira",
    groupsecretary: "Hadija Hassan",
    groupLocation: "Matopeni",
    noofmembers: 25,
    grant: 654000,
    loan: 215600,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d392b",
    },
    username: "johnmakola",
    groupno: "gl007",
    groupname: "Walimu Group",
    grouptype: "Work",
    groupdescription: "A Primary School and Local Secondary Teachers Group",
    groupadmin: "Fatma Huka",
    grouptreasurer: "Regina Karuku",
    groupsecretary: "Sori Dima",
    groupLocation: "Umoja",

    noofmembers: 35,
    grant: 785000,
    loan: 462000,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d392c",
    },
    username: "johnmakola",
    groupno: "gl008",
    groupname: "Biashara Group",
    grouptype: "Business",
    groupdescription: "A Business Men andWomen Investment Group ",
    groupadmin: "Adan Jaso",
    grouptreasurer: "Beatrice Asili",
    groupsecretary: "Beth Kinya",
    groupLocation: "Wendani",

    noofmembers: 14,
    grant: 254000,
    loan: 352000,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d392d",
    },
    username: "johnmakola",
    groupno: "gl009",
    groupname: "Jenga Mama Group",
    grouptype: "Business",
    groupdescription: "A Women Empowerment group for Small Businesses",
    groupadmin: "Adan Golicha",
    grouptreasurer: "Stella Wanja",
    groupsecretary: "Hadija Hassan",
    groupLocation: "Kahawa",

    noofmembers: 26,
    grant: 325900,
    loan: 78500,
  },
  {
    _id: {
      $oid: "63418486d0e121671e4d392e",
    },
    username: "johnmakola",
    groupno: "gl010",
    groupname: "Jirani Mwema",
    grouptype: "Community",
    groupdescription: "A Social  Welfare Group",
    groupadmin: "Jane Njeri",
    grouptreasurer: "James Karithi",
    groupsecretary: "Stella Wanja",
    groupLocation: "Kasarani",
    noofmembers: 45,
    grant: 626500,
    loan: 450200,
  },
];

export function getGroups() {
  return Groups;
}
